// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYZYFy6OQf39A9wPcAIpCBqR2PQgUInJI',
    appId: '1:160794690317:web:506742cd694e2e9807e644',
    messagingSenderId: '160794690317',
    projectId: 'dalimaster-5d226',
    authDomain: 'dalimaster-5d226.firebaseapp.com',
    storageBucket: 'dalimaster-5d226.firebasestorage.app',
    measurementId: 'G-4J91MSHV6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMI447_Ag3lf9iJ_GM1FZzn3Zx1znk68',
    appId: '1:160794690317:android:6cfabb39b7aa187c07e644',
    messagingSenderId: '160794690317',
    projectId: 'dalimaster-5d226',
    storageBucket: 'dalimaster-5d226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnfJpQCFAHqv9Lq6wmgXLQxWHfIBURwPM',
    appId: '1:160794690317:ios:9bd91c2741e435c507e644',
    messagingSenderId: '160794690317',
    projectId: 'dalimaster-5d226',
    storageBucket: 'dalimaster-5d226.firebasestorage.app',
    iosBundleId: 'org.tonycloud.dalimaster.dalimaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnfJpQCFAHqv9Lq6wmgXLQxWHfIBURwPM',
    appId: '1:160794690317:ios:9bd91c2741e435c507e644',
    messagingSenderId: '160794690317',
    projectId: 'dalimaster-5d226',
    storageBucket: 'dalimaster-5d226.firebasestorage.app',
    iosBundleId: 'org.tonycloud.dalimaster.dalimaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYZYFy6OQf39A9wPcAIpCBqR2PQgUInJI',
    appId: '1:160794690317:web:4e7428b4bf05dc4b07e644',
    messagingSenderId: '160794690317',
    projectId: 'dalimaster-5d226',
    authDomain: 'dalimaster-5d226.firebaseapp.com',
    storageBucket: 'dalimaster-5d226.firebasestorage.app',
    measurementId: 'G-41R11VW346',
  );
}
